"""Schemas package initialization."""
from apps.api.app.schemas.permission import (
    PermissionBase,
    PermissionCreate,
    PermissionResponse,
    PermissionGroup,
)
from apps.api.app.schemas.role import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleResponse,
    RoleWithCounts,
)
from apps.api.app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    UserPINLogin,
    UserQRLogin,
    StaffInvite,
    TokenResponse,
)
from apps.api.app.schemas.staff import (
    StaffStatus,
    StaffBase,
    StaffCreate,
    StaffUpdate,
    StaffResponse,
    StaffWithUserResponse,
)
from apps.api.app.schemas.shift import (
    ShiftStatus,
    AttendanceStatus,
    StaffShiftBase,
    StaffShiftCreate,
    StaffShiftUpdate,
    StaffShiftResponse,
    StaffCheckIn,
    StaffCheckOut,
)
from apps.api.app.schemas.invitation import (
    StaffInviteBase,
    StaffInviteCreate,
    StaffInviteResponse,
    AcceptInvitationRequest,
)

__all__ = [
    "PermissionBase",
    "PermissionCreate",
    "PermissionResponse",
    "PermissionGroup",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RoleResponse",
    "RoleWithCounts",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "UserPINLogin",
    "UserQRLogin",
    "StaffInvite",
    "TokenResponse",
    "StaffStatus",
    "StaffBase",
    "StaffCreate",
    "StaffUpdate",
    "StaffResponse",
    "StaffWithUserResponse",
    "ShiftStatus",
    "AttendanceStatus",
    "StaffShiftBase",
    "StaffShiftCreate",
    "StaffShiftUpdate",
    "StaffShiftResponse",
    "StaffCheckIn",
    "StaffCheckOut",
    "StaffInviteBase",
    "StaffInviteCreate",
    "StaffInviteResponse",
    "AcceptInvitationRequest",
]
