"""Add course pacing columns

Revision ID: 6530aeb7b158
Revises: 8ee6ea06d509
Create Date: 2026-06-15 19:45:35.554110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6530aeb7b158'
down_revision: Union[str, None] = '8ee6ea06d509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occasion_menus',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='occasion_date_check'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occasion_menu_items',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('occasion_menu_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('special_price >= 0', name='occasion_price_check_v2'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['occasion_menu_id'], ['occasion_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('occasion_menu_id', 'menu_item_id')
    )
    op.create_table('qr_code_scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_transfer_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('source_table_id', sa.UUID(), nullable=True),
    sa.Column('target_table_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('target_session_id', sa.UUID(), nullable=True),
    sa.Column('transferred_by', sa.UUID(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_session_id'], ['customer_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_session_id'], ['customer_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transferred_by'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kitchen_stations')
    op.drop_table('station_prep_times')
    op.drop_table('table_transfers')
    op.drop_table('kitchen_routing_rules')
    op.drop_table('item_transfers')
    op.drop_table('kitchen_display_settings')
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('categories', 'is_active')
    op.add_column('customer_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('customer_sessions', 'order_number')
    op.drop_column('customer_sessions', 'device_fingerprint')
    op.add_column('menu_item_modifiers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('menu_item_modifiers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('menu_items', sa.Column('is_vegetarian', sa.Boolean(), nullable=False))
    op.add_column('menu_items', sa.Column('is_spicy', sa.Boolean(), nullable=False))
    op.add_column('menu_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('menu_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('menu_items', 'dietary_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('fk_menu_items_station_id', 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'is_popular')
    op.drop_column('menu_items', 'is_active')
    op.drop_column('menu_items', 'station_id')
    op.add_column('order_item_modifiers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('order_items', sa.Column('served_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('order_items', 'start_delay_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('order_items', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'is_held',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'hold_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id', 'order_created_at'], ['id', 'created_at'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('customer_rating', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('orders', 'order_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.drop_column('orders', 'waiter_notes')
    op.drop_constraint('payments_cashier_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'cash_received')
    op.drop_column('payments', 'cashier_id')
    op.drop_column('payments', 'change_given')
    op.add_column('restaurants', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('restaurants', sa.Column('business_registration', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('kra_pin', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('subscription_status', postgresql.ENUM('trial', 'active', 'suspended', 'cancelled', name='subscription_status_enum'), nullable=False))
    op.add_column('restaurants', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_restaurants_deleted_by', 'restaurants', 'staff', ['deleted_by'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('restaurants', 'is_onboarded')
    op.drop_column('restaurants', 'status')
    op.add_column('staff', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('staff', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('fk_staff_kitchen_station_id', 'staff', type_='foreignkey')
    op.drop_column('staff', 'kitchen_station_id')
    op.drop_column('staff', 'kitchen_station')
    op.add_column('staff_activity_logs', sa.Column('shift_type_actual', postgresql.ENUM('morning', 'afternoon', 'evening', 'night', 'full', name='shift_type_enum'), nullable=True))
    op.add_column('table_transfer_logs', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('table_transfer_logs', sa.Column('transferred_by_staff_id', sa.UUID(), nullable=False))
    op.alter_column('table_transfer_logs', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('table_transfer_logs', 'original_table_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('table_transfer_logs', 'new_table_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('table_transfer_logs', 'transferred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('table_transfer_logs_order_id_fkey', 'table_transfer_logs', type_='foreignkey')
    op.drop_constraint('table_transfer_logs_transferred_by_fkey', 'table_transfer_logs', type_='foreignkey')
    op.create_foreign_key(None, 'table_transfer_logs', 'customer_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'table_transfer_logs', 'staff', ['transferred_by_staff_id'], ['id'], ondelete='CASCADE')
    op.drop_column('table_transfer_logs', 'transferred_by')
    op.drop_column('table_transfer_logs', 'order_id')
    op.add_column('tables', sa.Column('qr_code_printed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tables', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('waiter_calls', sa.Column('call_type', postgresql.ENUM('assistance', 'water', 'bill', 'other', name='call_type_enum'), nullable=False))
    op.add_column('waiter_calls', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('waiter_calls', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('waiter_calls', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('waiter_calls', 'status',
               existing_type=sa.TEXT(),
               type_=postgresql.ENUM('pending', 'acknowledged', 'completed', name='call_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waiter_calls', 'status',
               existing_type=postgresql.ENUM('pending', 'acknowledged', 'completed', name='call_status_enum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('waiter_calls', 'updated_at')
    op.drop_column('waiter_calls', 'completed_at')
    op.drop_column('waiter_calls', 'acknowledged_at')
    op.drop_column('waiter_calls', 'call_type')
    op.drop_column('tables', 'updated_at')
    op.drop_column('tables', 'qr_code_printed_at')
    op.add_column('table_transfer_logs', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('table_transfer_logs', sa.Column('transferred_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'table_transfer_logs', type_='foreignkey')
    op.drop_constraint(None, 'table_transfer_logs', type_='foreignkey')
    op.create_foreign_key('table_transfer_logs_transferred_by_fkey', 'table_transfer_logs', 'staff', ['transferred_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('table_transfer_logs_order_id_fkey', 'table_transfer_logs', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('table_transfer_logs', 'transferred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('table_transfer_logs', 'new_table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('table_transfer_logs', 'original_table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('table_transfer_logs', 'restaurant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('table_transfer_logs', 'transferred_by_staff_id')
    op.drop_column('table_transfer_logs', 'session_id')
    op.drop_column('staff_activity_logs', 'shift_type_actual')
    op.add_column('staff', sa.Column('kitchen_station', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('kitchen_station_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_staff_kitchen_station_id', 'staff', 'kitchen_stations', ['kitchen_station_id'], ['id'], ondelete='SET NULL')
    op.alter_column('staff', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('staff', 'updated_at')
    op.drop_column('staff', 'last_active_at')
    op.add_column('restaurants', sa.Column('status', postgresql.ENUM('active', 'expired', 'trial', name='subscription_status_enum'), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('is_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_restaurants_deleted_by', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'deleted_by')
    op.drop_column('restaurants', 'subscription_status')
    op.drop_column('restaurants', 'city')
    op.drop_column('restaurants', 'kra_pin')
    op.drop_column('restaurants', 'business_registration')
    op.drop_column('restaurants', 'subscription_ends_at')
    op.add_column('payments', sa.Column('change_given', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('cashier_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('cash_received', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_cashier_id_fkey', 'payments', 'staff', ['cashier_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('waiter_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('orders', 'order_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'customer_rating')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'notes')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_items', 'hold_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('order_items', 'is_held',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'start_delay_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'created_at')
    op.drop_column('order_items', 'served_at')
    op.drop_column('order_items', 'order_created_at')
    op.drop_column('order_item_modifiers', 'created_at')
    op.add_column('menu_items', sa.Column('station_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('menu_items', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('menu_items', sa.Column('is_popular', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_menu_items_station_id', 'menu_items', 'kitchen_stations', ['station_id'], ['id'], ondelete='SET NULL')
    op.alter_column('menu_items', 'dietary_info',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('menu_items', 'updated_at')
    op.drop_column('menu_items', 'created_at')
    op.drop_column('menu_items', 'is_spicy')
    op.drop_column('menu_items', 'is_vegetarian')
    op.drop_column('menu_item_modifiers', 'updated_at')
    op.drop_column('menu_item_modifiers', 'created_at')
    op.add_column('customer_sessions', sa.Column('device_fingerprint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customer_sessions', sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('customer_sessions', 'updated_at')
    op.add_column('categories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'description')
    op.create_table('kitchen_display_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sound_alerts_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('new_order_volume', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=False),
    sa.Column('ready_order_volume', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'dark'::character varying"), autoincrement=False, nullable=False),
    sa.Column('font_size', sa.VARCHAR(length=10), server_default=sa.text("'large'::character varying"), autoincrement=False, nullable=False),
    sa.Column('show_timer', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('show_modifiers', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('auto_accept', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('prep_time_buffer_percent', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='kitchen_display_settings_restaurant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['kitchen_stations.id'], name='kitchen_display_settings_station_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kitchen_display_settings_pkey')
    )
    op.create_table('item_transfers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('from_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transferred_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transferred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_session_id'], ['customer_sessions.id'], name='item_transfers_from_session_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name='item_transfers_order_item_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='item_transfers_restaurant_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_session_id'], ['customer_sessions.id'], name='item_transfers_to_session_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transferred_by'], ['staff.id'], name='item_transfers_transferred_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='item_transfers_pkey')
    )
    op.create_table('kitchen_routing_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_station_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('target_station_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_keyword', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='kitchen_routing_rules_restaurant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_station_id'], ['kitchen_stations.id'], name='kitchen_routing_rules_source_station_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_station_id'], ['kitchen_stations.id'], name='kitchen_routing_rules_target_station_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kitchen_routing_rules_pkey')
    )
    op.create_table('table_transfers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('original_table_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('new_table_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transferred_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transferred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['new_table_id'], ['tables.id'], name='table_transfers_new_table_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='table_transfers_order_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_table_id'], ['tables.id'], name='table_transfers_original_table_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='table_transfers_restaurant_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transferred_by'], ['staff.id'], name='table_transfers_transferred_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='table_transfers_pkey')
    )
    op.create_table('station_prep_times',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('default_seconds', sa.INTEGER(), server_default=sa.text('600'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='station_prep_times_restaurant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['kitchen_stations.id'], name='station_prep_times_station_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='station_prep_times_pkey')
    )
    op.create_table('kitchen_stations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('station_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='kitchen_stations_restaurant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='kitchen_stations_pkey')
    )
    op.drop_table('item_transfer_logs')
    op.drop_table('qr_code_scans')
    op.drop_table('occasion_menu_items')
    op.drop_table('inventory_logs')
    op.drop_table('occasion_menus')
    # ### end Alembic commands ###
